spring.application.name=order-service
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/orderdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

enable.swagger.plugin=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
server.port:8083

# Enable Feign logging
logging.level.com.example.order.client=DEBUG
